export type Database = {
  public: {
    Tables: {
      payment_instructions: {
        Row: {
          id: string;
          partner_id: string;
          booking_id: string;
          driver_id: string;
          driver_name: string | null;
          vehicle_reg: string | null;
          amount: number;
          method: 'bank_transfer' | 'direct_debit';
          frequency: 'weekly' | 'one_off';
          type: 'weekly_rent' | 'deposit' | 'refund' | 'topup' | 'adjustment';
          next_due_date: string | null;
          status: 'pending' | 'sent' | 'auto' | 'void' | 'deposit_pending' | 'deposit_refund_pending' | 'deposit_refunded' | 'deposit_received';
          last_sent_at: string | null;
          refunded_amount: number | null;
          reason: string | null;
          metadata: any;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          partner_id: string;
          booking_id: string;
          driver_id: string;
          driver_name?: string | null;
          vehicle_reg?: string | null;
          amount: number;
          method?: 'bank_transfer' | 'direct_debit';
          frequency?: 'weekly' | 'one_off';
          type?: 'weekly_rent' | 'deposit' | 'refund' | 'topup' | 'adjustment';
          next_due_date?: string | null;
          status?: 'pending' | 'sent' | 'auto' | 'void' | 'deposit_pending' | 'deposit_refund_pending' | 'deposit_refunded' | 'deposit_received';
          last_sent_at?: string | null;
          refunded_amount?: number | null;
          reason?: string | null;
          metadata?: any;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          partner_id?: string;
          booking_id?: string;
          driver_id?: string;
          driver_name?: string | null;
          vehicle_reg?: string | null;
          amount?: number;
          method?: 'bank_transfer' | 'direct_debit';
          frequency?: 'weekly' | 'one_off';
          type?: 'weekly_rent' | 'deposit' | 'refund' | 'topup' | 'adjustment';
          next_due_date?: string | null;
          status?: 'pending' | 'sent' | 'auto' | 'void' | 'deposit_pending' | 'deposit_refund_pending' | 'deposit_refunded' | 'deposit_received';
          last_sent_at?: string | null;
          refunded_amount?: number | null;
          reason?: string | null;
          metadata?: any;
          created_at?: string;
          updated_at?: string;
        };
      };
      partners: {
        Row: {
          id: string;
          user_id: string;
          company_name: string;
          business_type: string;
          tax_id: string | null;
          address: string;
          city: string;
          state: string;
          country: string;
          postal_code: string;
          phone: string;
          website: string | null;
          description: string | null;
          logo: string | null;
          is_approved: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          company_name: string;
          business_type: string;
          tax_id?: string | null;
          address: string;
          city: string;
          state: string;
          country: string;
          postal_code: string;
          phone: string;
          website?: string | null;
          description?: string | null;
          logo?: string | null;
          is_approved?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          company_name?: string;
          business_type?: string;
          tax_id?: string | null;
          address?: string;
          city?: string;
          state?: string;
          country?: string;
          postal_code?: string;
          phone?: string;
          website?: string | null;
          description?: string | null;
          logo?: string | null;
          is_approved?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      partner_staff: {
        Row: {
          id: string;
          partner_id: string;
          user_id: string;
          role: string;
          department: string | null;
          position: string | null;
          start_date: string | null;
          salary: number | null;
          address: string | null;
          emergency_contact_name: string | null;
          emergency_contact_phone: string | null;
          emergency_contact_relationship: string | null;
          notes: string | null;
          last_login: string | null;
          login_count: number | null;
          permissions: any;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          partner_id: string;
          user_id: string;
          role: string;
          department?: string | null;
          position?: string | null;
          start_date?: string | null;
          salary?: number | null;
          address?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          emergency_contact_relationship?: string | null;
          notes?: string | null;
          last_login?: string | null;
          login_count?: number | null;
          permissions?: any;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          partner_id?: string;
          user_id?: string;
          role?: string;
          department?: string | null;
          position?: string | null;
          start_date?: string | null;
          salary?: number | null;
          address?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          emergency_contact_relationship?: string | null;
          notes?: string | null;
          last_login?: string | null;
          login_count?: number | null;
          permissions?: any;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      bookings: {
        Row: {
          id: string;
          user_id: string;
          partner_id: string;
          driver_id: string;
          vehicle_id: string;
          start_date: string;
          end_date: string;
          status: string;
          total_amount: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          partner_id: string;
          driver_id: string;
          vehicle_id: string;
          start_date: string;
          end_date: string;
          status?: string;
          total_amount: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          partner_id?: string;
          driver_id?: string;
          vehicle_id?: string;
          start_date?: string;
          end_date?: string;
          status?: string;
          total_amount?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      vehicles: {
        Row: {
          id: string;
          partner_id: string;
          driver_id: string | null;
          name: string | null;
          make: string | null;
          model: string | null;
          year: number | null;
          license_plate: string | null;
          vin: string | null;
          color: string | null;
          fuel_type: string | null;
          transmission: string | null;
          seats: number | null;
          doors: number | null;
          mileage: number | null;
          engine: string | null;
          location: string | null;
          description: string | null;
          daily_rate: number | null;
          weekly_rate: number | null;
          monthly_rate: number | null;
          price_per_week: number | null;
          price_per_day: number | null;
          category: string | null;
          image_urls: string[];
          features: string[];
          insurance_expiry: string | null;
          mot_expiry: string | null;
          road_tax_expiry: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          partner_id: string;
          driver_id?: string | null;
          name?: string | null;
          make?: string | null;
          model?: string | null;
          year?: number | null;
          license_plate?: string | null;
          vin?: string | null;
          color?: string | null;
          fuel_type?: string | null;
          transmission?: string | null;
          seats?: number | null;
          doors?: number | null;
          mileage?: number | null;
          engine?: string | null;
          location?: string | null;
          description?: string | null;
          daily_rate?: number | null;
          weekly_rate?: number | null;
          monthly_rate?: number | null;
          price_per_week?: number | null;
          price_per_day?: number | null;
          category?: string | null;
          image_urls?: string[];
          features?: string[];
          insurance_expiry?: string | null;
          mot_expiry?: string | null;
          road_tax_expiry?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          partner_id?: string;
          driver_id?: string | null;
          name?: string | null;
          make?: string | null;
          model?: string | null;
          year?: number | null;
          license_plate?: string | null;
          vin?: string | null;
          color?: string | null;
          fuel_type?: string | null;
          transmission?: string | null;
          seats?: number | null;
          doors?: number | null;
          mileage?: number | null;
          engine?: string | null;
          location?: string | null;
          description?: string | null;
          daily_rate?: number | null;
          weekly_rate?: number | null;
          monthly_rate?: number | null;
          price_per_week?: number | null;
          price_per_day?: number | null;
          category?: string | null;
          image_urls?: string[];
          features?: string[];
          insurance_expiry?: string | null;
          mot_expiry?: string | null;
          road_tax_expiry?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      payments: {
        Row: {
          id: string;
          booking_id: string;
          user_id: string;
          partner_id: string;
          driver_id: string;
          amount: number;
          currency: string;
          payment_method: string;
          status: string;
          transaction_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          user_id: string;
          partner_id: string;
          driver_id: string;
          amount: number;
          currency?: string;
          payment_method?: string;
          status?: string;
          transaction_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          booking_id?: string;
          user_id?: string;
          partner_id?: string;
          driver_id?: string;
          amount?: number;
          currency?: string;
          payment_method?: string;
          status?: string;
          transaction_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      users: {
        Row: {
          id: string;
          email: string;
          phone: string | null;
          first_name: string;
          last_name: string;
          avatar: string | null;
          role: string;
          is_active: boolean;
          is_verified: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          phone?: string | null;
          first_name: string;
          last_name: string;
          avatar?: string | null;
          role?: string;
          is_active?: boolean;
          is_verified?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          phone?: string | null;
          first_name?: string;
          last_name?: string;
          avatar?: string | null;
          role?: string;
          is_active?: boolean;
          is_verified?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      cars: {
        Row: {
          id: string;
          name: string;
          make: string;
          model: string;
          year: number;
          price_per_day: number;
          price_per_week: number;
          sale_price_per_week: number | null;
          image_url: string;
          image_urls: string[] | null;
          features: string[];
          category: string;
          is_available: boolean;
          status: string | null;
          insurance_included: boolean | null;
          fuel_type: string | null;
          min_term_months: number | null;
          deposit_required: boolean | null;
          deposit_amount: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          make: string;
          model: string;
          year: number;
          price_per_day: number;
          price_per_week: number;
          sale_price_per_week?: number | null;
          image_url: string;
          image_urls?: string[] | null;
          features?: string[];
          category?: string;
          is_available?: boolean;
          status?: string | null;
          insurance_included?: boolean | null;
          fuel_type?: string | null;
          min_term_months?: number | null;
          deposit_required?: boolean | null;
          deposit_amount?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          make?: string;
          model?: string;
          year?: number;
          price_per_day?: number;
          price_per_week?: number;
          sale_price_per_week?: number | null;
          image_url?: string;
          image_urls?: string[] | null;
          features?: string[];
          category?: string;
          is_available?: boolean;
          status?: string | null;
          insurance_included?: boolean | null;
          fuel_type?: string | null;
          min_term_months?: number | null;
          deposit_required?: boolean | null;
          deposit_amount?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      saved_cars: {
        Row: {
          id: string;
          user_id: string;
          car_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          car_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          car_id?: string;
          created_at?: string;
        };
      };
      // Added definitions for analytics reporting tables
      reports: {
        Row: {
          id: string;
          title: string;
          type: 'financial' | 'operational' | 'performance' | 'compliance';
          status: 'generated' | 'pending' | 'failed';
          file_size: string;
          format: 'pdf' | 'csv' | 'excel';
          file_url: string | null;
          created_at: string;
          updated_at: string;
          generated_by: string | null;
          data: any;
        };
        Insert: {
          id?: string;
          title: string;
          type?: 'financial' | 'operational' | 'performance' | 'compliance';
          status?: 'generated' | 'pending' | 'failed';
          file_size?: string;
          format?: 'pdf' | 'csv' | 'excel';
          file_url?: string | null;
          created_at?: string;
          updated_at?: string;
          generated_by?: string | null;
          data?: any;
        };
        Update: {
          id?: string;
          title?: string;
          type?: 'financial' | 'operational' | 'performance' | 'compliance';
          status?: 'generated' | 'pending' | 'failed';
          file_size?: string;
          format?: 'pdf' | 'csv' | 'excel';
          file_url?: string | null;
          created_at?: string;
          updated_at?: string;
          generated_by?: string | null;
          data?: any;
        };
      };

      report_templates: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          category: 'financial' | 'operational' | 'performance' | 'compliance';
          frequency: 'daily' | 'weekly' | 'monthly' | 'quarterly';
          last_generated: string | null;
          next_generation: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          template_data: any;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          category?: 'financial' | 'operational' | 'performance' | 'compliance';
          frequency?: 'daily' | 'weekly' | 'monthly' | 'quarterly';
          last_generated?: string | null;
          next_generation?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          template_data?: any;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          category?: 'financial' | 'operational' | 'performance' | 'compliance';
          frequency?: 'daily' | 'weekly' | 'monthly' | 'quarterly';
          last_generated?: string | null;
          next_generation?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          template_data?: any;
        };
      };
    };
  };
};
