import { NextRequest, NextResponse } from 'next/server';

export async function GET(request: NextRequest) {
  try {
    // Create a simple HTML response that looks like a report
    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Report Placeholder</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 40px; }
            .header { text-align: center; margin-bottom: 30px; }
            .content { line-height: 1.6; }
            .footer { margin-top: 40px; text-align: center; color: #666; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>📊 PCO Analytics Report</h1>
            <p>Generated on ${new Date().toLocaleDateString()}</p>
          </div>
          <div class="content">
            <h2>Report Summary</h2>
            <p>This is a placeholder report generated by the ComparePCO Analytics System. In a real implementation, this would contain actual data and analytics from your Supabase database.</p>
            
            <h3>Report Information</h3>
            <ul>
              <li>Report Type: Analytics Summary</li>
              <li>Generated Date: ${new Date().toLocaleDateString()}</li>
              <li>Data Source: Supabase Database</li>
              <li>Status: Placeholder</li>
            </ul>
            
            <h3>System Information</h3>
            <p>The ComparePCO Analytics System is designed to provide comprehensive insights into PCO car rental operations, including booking analytics, revenue tracking, and performance metrics.</p>
          </div>
          <div class="footer">
            <p>Generated by ComparePCO Analytics System</p>
          </div>
        </body>
      </html>
    `;

    return new NextResponse(htmlContent, {
      status: 200,
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': 'inline; filename="report.html"'
      }
    });
  } catch (error) {
    console.error('Error generating placeholder report:', error);
    return NextResponse.json(
      { error: 'Failed to generate placeholder report' },
      { status: 500 }
    );
  }
} 